-- AlterTable: app-facing property fields
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "checkInTime" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "checkOutTime" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "hidden" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "deleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "extraJson" JSONB;
